src/gz chaos_calmer_base https://archive.openwrt.org/chaos_calmer/15.05/ramips/rt305x/packages/base
src/gz chaos_calmer_luci https://archive.openwrt.org/chaos_calmer/15.05/ramips/rt305x/packages/luci
src/gz chaos_calmer_management https://archive.openwrt.org/chaos_calmer/15.05/ramips/rt305x/packages/management
src/gz chaos_calmer_packages https://archive.openwrt.org/chaos_calmer/15.05/ramips/rt305x/packages/packages
src/gz chaos_calmer_routing https://archive.openwrt.org/chaos_calmer/15.05/ramips/rt305x/packages/routing
src/gz chaos_calmer_telephony https://archive.openwrt.org/chaos_calmer/15.05/ramips/rt305x/packages/telephony
